version: '3'
services:
    infclass:
        build: ./
        restart: always
        ports:
            - "127.0.0.1:8002:8002"
        environment:
            - SERVER_IP=${SERVER_IP}
            - ECON_PORT=${ECON_PORT}
            - ECON_PASSWORD=${ECON_PASSWORD}
            - MYSQL_USER=${DB_USER:-user}
            - MYSQL_PASSWORD=${DB_PASS:-pass}
            - MYSQL_DB=${DB_NAME:-infclass}

    infclass_db:
        image: mariadb:10.3.29
        restart: always
        volumes:
          - infclass_data:/var/lib/mysql
        ports:
            - "127.0.0.1:3306:3306"
        environment:
            - MARIADB_ROOT_PASSWORD=${DB_PASS:-pass}
            - MARIADB_USER=${DB_USER:-user}
            - MARIADB_PASSWORD=${DB_PASS:-pass}
            - MARIADB_DATABASE=${DB_NAME:-infclass}
    
    infclass_web:
        build: ./web
        ports:
            - "127.0.0.1:82:80"


volumes:
    infclass_data:
