name: Build images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          USER: ${{ github.actor }}
          TOKEN: ${{ github.token }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: USER,TOKEN
          script: |
            git clone git@github.com:ResamVi/infclass-stats.git repo
            docker build repo/. -t ghcr.io/resamvi/infclassci:latest
            docker build repo/web/. -t ghcr.io/resamvi/infclassci_web:latest
            rm -rf repo