name: Build images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          ECON_PORT: ${{ secrets.ECON_PORT }}
          ECON_PASSWORD: ${{ secrets.ECON_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: SERVER_IP,ECON_PORT,ECON_PASSWORD
          script: |
            export SERVER_IP=$SERVER_IP
            export ECON_PORT=$ECON_PORT
            export ECON_PASSWORD=$ECON_PASSWORD
            git clone git@github.com:ResamVi/infclass-stats.git repo
            docker-compose -p infclass -f repo/docker-compose.yml down
            docker-compose -p infclass -f repo/docker-compose.yml up --detach --build --force-recreate
            rm -rf repo