name: Build images

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          ECON_PORT: ${{ secrets.ECON_PORT }}
          ECON_PASSWORD: ${{ secrets.ECON_PASSWORD }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: SERVER_IP,ECON_PORT,ECON_PASSWORD,DB_USER,DB_PASS,DB_NAME
          script: |
            echo $SERVER_IP | sed 's/./& /g'
            git clone git@github.com:ResamVi/infclass-stats.git repo
            docker-compose -p infclass -f repo/docker-compose.yml up --detach --build --force-recreate
            rm -rf repo